name: Rust (Windows)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --release --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Prepare output directory
      run: |
        mkdir output
        copy target\release\<your_binary_name>.exe output\
        if exist static     xcopy static     output\static     /E /I /Y
        if exist templates  xcopy templates  output\templates  /E /I /Y
        if exist web        xcopy web        output\web        /E /I /Y
      shell: cmd

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-bundle
        path: output

